service: nasa-mars-robot

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      managedPolicies:
        - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'

functions:
  webhook:
    handler: webhook.handler
    events:
      - http:
          path: webhook
          method: post
  scraper:
    handler: scraper.handler
  idmanager:
    handler: idmanager.handler
  updatechecker:
    handler: updatechecker.handler
  contentalarm:
    handler: contentalarm.handler